#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
03e_make_final_erp_figures.py

Final ERP figure generator for the LEMON/MELON Emotional Affect analysis.

This script creates clean, report/paper-ready figures from the outputs that have
already been generated by the ERP pipeline.

Recommended run:
    python scripts/03e_make_final_erp_figures.py --config configs/config.yaml

Expected inputs:
    reports/erp_diff_sens/*_grand_average.csv
    reports/stats_sens/subject_level_window_differences.csv
    reports/stats_sens/subject_level_difference_stats.csv
    reports/stats_sens/w4_w5_interpretation_summary.csv

Main outputs:
    reports/final_figures/figure_01_face_nonface_difference_waves.png
    reports/final_figures/figure_02_subject_level_w4_boxplot.png
    reports/final_figures/figure_03_w4_w5_summary.png
    reports/final_figures/figure_04_w4_w5_paired_subjects.png
    reports/final_figures/final_figure_source_values.csv
    reports/final_figures/final_w4_w5_paired_stats.csv

Scientific focus:
    Face - Non-face, with emphasis on W4 = 320-600 ms and W5 = 600-800 ms.

Notes:
    - Emotional - Neutral is intentionally not treated as the main figure here,
      because previous analyses showed it is weaker and less stable.
    - The script is designed to be robust to slightly different column names in
      grand-average CSV files.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd

try:
    import yaml
except Exception:
    yaml = None

try:
    import matplotlib.pyplot as plt
except Exception as exc:
    raise RuntimeError("matplotlib is required for final figure generation.") from exc

try:
    from scipy import stats
except Exception:
    stats = None


# ---------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------

DEFAULT_WINDOWS_MS = {
    "W1": [80, 130],
    "W2": [130, 220],
    "W3": [220, 320],
    "W4": [320, 600],
    "W5": [600, 800],
}

# Main panels for the final difference-wave figure.
DIFF_WAVE_PANELS = [
    {
        "modality": "scalp_sens",
        "contrast": "face_vs_nonface",
        "roi": "late_roi",
        "title": "Scalp EEG: late ROI",
        "interpretation": "Primary scalp W4 effect",
    },
    {
        "modality": "scalp_sens",
        "contrast": "face_vs_nonface",
        "roi": "face_roi",
        "title": "Scalp EEG: face ROI",
        "interpretation": "Early/face-related ROI",
    },
    {
        "modality": "ear_strict_sens",
        "contrast": "face_vs_nonface",
        "roi": "ear_strict",
        "title": "Ear-EEG: strict-ear montage",
        "interpretation": "Ear effect without Fpz",
    },
    {
        "modality": "ear_full_sens",
        "contrast": "face_vs_nonface",
        "roi": "ear_right",
        "title": "Ear-EEG: right-ear ROI",
        "interpretation": "Strongest ear-side effect",
    },
]

# Key rows for subject-level W4 and W4/W5 summary figures.
KEY_EFFECTS = [
    ("scalp_sens", "late_roi", "Scalp\nlate ROI"),
    ("scalp_sens", "face_roi", "Scalp\nface ROI"),
    ("scalp_sens", "central_roi", "Scalp\ncentral ROI"),
    ("ear_strict_sens", "ear_strict", "Ear\nstrict"),
    ("ear_full_sens", "ear_right", "Ear\nright"),
    ("ear_full_sens", "ear_full", "Ear\nfull"),
]


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

def load_yaml(path: Path) -> dict:
    if not path.exists() or yaml is None:
        return {}
    with path.open("r", encoding="utf-8") as f:
        obj = yaml.safe_load(f)
    return obj or {}


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def get_project_root(config: dict) -> Path:
    for key in ["root", "root_dir", "data_root", "bids_root", "project_root"]:
        if config.get(key):
            return Path(config[key])
    return Path.cwd()


def get_windows(config: dict) -> Dict[str, List[float]]:
    windows = (
        config.get("erp_windows_ms")
        or config.get("erp_windows")
        or config.get("windows")
        or DEFAULT_WINDOWS_MS
    )
    windows = {str(k): list(v) for k, v in windows.items()}
    if "W5" not in windows:
        windows["W5"] = [600, 800]
    return windows


def find_first_existing(paths: Iterable[Path]) -> Optional[Path]:
    for p in paths:
        if p.exists():
            return p
    return None


def infer_column(df: pd.DataFrame, candidates: Iterable[str], required: bool = True) -> Optional[str]:
    lower = {c.lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lower:
            return lower[c.lower()]
    # Partial matching fallback
    for c in df.columns:
        cl = c.lower()
        for cand in candidates:
            if cand.lower() in cl:
                return c
    if required:
        raise ValueError(f"Could not infer required column. Candidates: {list(candidates)}. Available: {list(df.columns)}")
    return None


def read_grand_average_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)

    time_col = infer_column(df, ["time_ms", "time", "times", "t_ms", "time_from_stimulus_ms"])
    mean_col = infer_column(df, ["mean_difference", "grand_mean", "mean", "difference", "diff_mean", "y"])
    sem_col = infer_column(df, ["sem", "sem_difference", "sem_average", "grand_sem", "stderr", "se"], required=False)

    out = pd.DataFrame({
        "time_ms": pd.to_numeric(df[time_col], errors="coerce"),
        "mean_difference": pd.to_numeric(df[mean_col], errors="coerce"),
    })

    if sem_col is not None:
        out["sem"] = pd.to_numeric(df[sem_col], errors="coerce")
    else:
        out["sem"] = np.nan

    out = out.dropna(subset=["time_ms", "mean_difference"]).sort_values("time_ms")
    return out


def grand_average_path(diff_dir: Path, modality: str, contrast: str, roi: str) -> Path:
    return diff_dir / f"{modality}_{contrast}_{roi}_grand_average.csv"


def safe_float(x) -> float:
    try:
        return float(x)
    except Exception:
        return np.nan


def bh_fdr(pvals: Iterable[float]) -> np.ndarray:
    p = np.asarray(list(pvals), dtype=float)
    out = np.full_like(p, np.nan, dtype=float)
    valid = np.isfinite(p)
    if valid.sum() == 0:
        return out
    pv = p[valid]
    order = np.argsort(pv)
    ranked = pv[order]
    m = len(ranked)
    adj = ranked * m / np.arange(1, m + 1)
    adj = np.minimum.accumulate(adj[::-1])[::-1]
    adj = np.clip(adj, 0, 1)
    corrected = np.empty_like(adj)
    corrected[order] = adj
    out[valid] = corrected
    return out


def paired_stats_for_w4_w5(subject_diffs: pd.DataFrame) -> pd.DataFrame:
    rows = []
    df = subject_diffs.copy()
    df["subject_id"] = df["subject_id"].astype(str)

    for modality, roi, label in KEY_EFFECTS:
        sub = df[
            (df["contrast"] == "face_vs_nonface")
            & (df["modality"] == modality)
            & (df["roi"] == roi)
            & (df["window"].isin(["W4", "W5"]))
        ].copy()

        if sub.empty:
            continue

        wide = sub.pivot_table(index="subject_id", columns="window", values="difference", aggfunc="mean")
        if "W4" not in wide.columns or "W5" not in wide.columns:
            continue

        wide = wide.dropna(subset=["W4", "W5"])
        if len(wide) == 0:
            continue

        diff = wide["W4"] - wide["W5"]
        n = len(diff)
        mean_w4 = safe_float(wide["W4"].mean())
        mean_w5 = safe_float(wide["W5"].mean())
        mean_drop = safe_float(diff.mean())
        sem_drop = safe_float(diff.std(ddof=1) / math.sqrt(n)) if n > 1 else np.nan

        if stats is not None and n > 1 and diff.std(ddof=1) > 0:
            t_res = stats.ttest_1samp(diff, 0.0)
            p_t = safe_float(t_res.pvalue)
            t_stat = safe_float(t_res.statistic)
            try:
                w_res = stats.wilcoxon(diff)
                p_w = safe_float(w_res.pvalue)
                w_stat = safe_float(w_res.statistic)
            except Exception:
                p_w = np.nan
                w_stat = np.nan
        else:
            t_stat = np.nan
            p_t = np.nan
            w_stat = np.nan
            p_w = np.nan

        n_pos = int((diff > 0).sum())
        n_neg = int((diff < 0).sum())
        dz = safe_float(diff.mean() / diff.std(ddof=1)) if n > 1 and diff.std(ddof=1) > 0 else np.nan

        rows.append({
            "modality": modality,
            "roi": roi,
            "label": label,
            "n_subjects": n,
            "mean_w4": mean_w4,
            "mean_w5": mean_w5,
            "mean_w4_minus_w5": mean_drop,
            "sem_w4_minus_w5": sem_drop,
            "n_w4_gt_w5": n_pos,
            "n_w4_lt_w5": n_neg,
            "positive_pct": 100 * n_pos / n if n else np.nan,
            "t_stat": t_stat,
            "p_ttest": p_t,
            "wilcoxon_stat": w_stat,
            "p_wilcoxon": p_w,
            "effect_size_dz": dz,
        })

    out = pd.DataFrame(rows)
    if len(out) > 0:
        out["p_fdr_ttest"] = bh_fdr(out["p_ttest"])
        out["p_fdr_wilcoxon"] = bh_fdr(out["p_wilcoxon"])
    return out


def label_for_pair(modality: str, roi: str) -> str:
    for m, r, label in KEY_EFFECTS:
        if m == modality and r == roi:
            return label
    return f"{modality}\n{roi}"


def add_windows_background(ax, windows: Dict[str, List[float]]) -> None:
    # Mark W4 and W5 most clearly; keep W1-W3 as light labels.
    if "W4" in windows:
        ax.axvspan(windows["W4"][0], windows["W4"][1], alpha=0.10, zorder=0)
        ytop = ax.get_ylim()[1]
        ax.text(np.mean(windows["W4"]), ytop * 0.94, "W4", ha="center", va="top", fontsize=9)
    if "W5" in windows:
        ax.axvspan(windows["W5"][0], windows["W5"][1], alpha=0.06, zorder=0)
        ytop = ax.get_ylim()[1]
        ax.text(np.mean(windows["W5"]), ytop * 0.94, "W5", ha="center", va="top", fontsize=9)
    for w in ["W1", "W2", "W3"]:
        if w in windows:
            ytop = ax.get_ylim()[1]
            ax.text(np.mean(windows[w]), ytop * 0.94, w, ha="center", va="top", fontsize=8)


def clean_label(s: str) -> str:
    return (
        str(s)
        .replace("_sens", "")
        .replace("_main", "")
        .replace("_", " ")
    )


# ---------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------

def figure_difference_waves(diff_dir: Path, out_dir: Path, windows: Dict[str, List[float]]) -> pd.DataFrame:
    source_rows = []

    fig, axes = plt.subplots(2, 2, figsize=(12, 7), sharex=True)
    axes = axes.flatten()

    for ax, panel in zip(axes, DIFF_WAVE_PANELS):
        p = grand_average_path(
            diff_dir,
            panel["modality"],
            panel["contrast"],
            panel["roi"],
        )

        if not p.exists():
            ax.set_title(f"Missing: {p.name}", fontsize=10)
            ax.axis("off")
            continue

        df = read_grand_average_csv(p)
        time = df["time_ms"].to_numpy()
        y = df["mean_difference"].to_numpy()
        sem = df["sem"].to_numpy()

        ax.plot(time, y, linewidth=2.0, label="Face - Non-face")
        if np.isfinite(sem).any():
            ax.fill_between(time, y - sem, y + sem, alpha=0.20, linewidth=0, label="± SEM")

        ax.axhline(0, linestyle="--", linewidth=1)
        ax.axvline(0, linestyle=":", linewidth=1)
        ax.set_title(panel["title"], fontsize=12)
        ax.set_xlim(-200, 800)
        ax.set_xlabel("Time from stimulus onset (ms)")
        ax.set_ylabel("Difference amplitude")
        add_windows_background(ax, windows)
        ax.legend(loc="upper left", fontsize=8, frameon=False)

        for _, r in df.iterrows():
            source_rows.append({
                "figure": "figure_01_face_nonface_difference_waves",
                "modality": panel["modality"],
                "contrast": panel["contrast"],
                "roi": panel["roi"],
                "time_ms": r["time_ms"],
                "mean_difference": r["mean_difference"],
                "sem": r["sem"],
                "source_file": str(p),
            })

    fig.suptitle("Face - Non-face ERP difference waves", fontsize=16)
    fig.tight_layout(rect=[0, 0, 1, 0.96])

    out_png = out_dir / "figure_01_face_nonface_difference_waves.png"
    out_pdf = out_dir / "figure_01_face_nonface_difference_waves.pdf"
    fig.savefig(out_png, dpi=300)
    fig.savefig(out_pdf)
    plt.close(fig)

    print(f"[OK] Wrote: {out_png}")
    print(f"[OK] Wrote: {out_pdf}")

    return pd.DataFrame(source_rows)


def figure_subject_w4_boxplot(subject_diffs: pd.DataFrame, out_dir: Path) -> None:
    df = subject_diffs[
        (subject_diffs["contrast"] == "face_vs_nonface")
        & (subject_diffs["window"] == "W4")
    ].copy()

    groups = []
    labels = []
    for modality, roi, label in KEY_EFFECTS:
        vals = df[(df["modality"] == modality) & (df["roi"] == roi)]["difference"].dropna().to_numpy()
        if len(vals) > 0:
            groups.append(vals)
            labels.append(label)

    fig, ax = plt.subplots(figsize=(10, 5.5))

    bp = ax.boxplot(groups, tick_labels=labels, showmeans=True, patch_artist=True)
    for patch in bp["boxes"]:
        patch.set_alpha(0.35)

    for i, vals in enumerate(groups, start=1):
        jitter = np.linspace(-0.08, 0.08, len(vals)) if len(vals) > 1 else np.array([0.0])
        ax.scatter(np.full(len(vals), i) + jitter, vals, s=26, alpha=0.75, zorder=3)

    ax.axhline(0, linestyle="--", linewidth=1)
    ax.set_title("Subject-level Face - Non-face differences in W4 (320-600 ms)", fontsize=14)
    ax.set_ylabel("Subject-level difference")
    ax.tick_params(axis="x", labelrotation=30)
    fig.tight_layout()

    out_png = out_dir / "figure_02_subject_level_w4_boxplot.png"
    out_pdf = out_dir / "figure_02_subject_level_w4_boxplot.pdf"
    fig.savefig(out_png, dpi=300)
    fig.savefig(out_pdf)
    plt.close(fig)

    print(f"[OK] Wrote: {out_png}")
    print(f"[OK] Wrote: {out_pdf}")


def figure_w4_w5_summary(w4w5: pd.DataFrame, out_dir: Path) -> None:
    df = w4w5.copy()
    rows = []
    for modality, roi, label in KEY_EFFECTS:
        sub = df[(df["modality"] == modality) & (df["roi"] == roi)]
        if len(sub) == 0:
            continue
        r = sub.iloc[0].to_dict()
        r["label"] = label
        rows.append(r)

    plot_df = pd.DataFrame(rows)
    if plot_df.empty:
        print("[WARN] No rows available for W4/W5 summary figure.")
        return

    x = np.arange(len(plot_df))
    width = 0.36

    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.bar(
        x - width / 2,
        plot_df["w4_mean_difference"],
        width,
        yerr=plot_df.get("w4_sem_average", np.nan),
        capsize=4,
        label="W4: 320-600 ms",
    )
    ax.bar(
        x + width / 2,
        plot_df["w5_mean_difference"],
        width,
        yerr=plot_df.get("w5_sem_average", np.nan),
        capsize=4,
        label="W5: 600-800 ms",
    )

    ax.axhline(0, linestyle="--", linewidth=1)
    ax.set_xticks(x)
    ax.set_xticklabels(plot_df["label"], rotation=30, ha="right")
    ax.set_ylabel("Grand-average difference")
    ax.set_title("Face - Non-face: W4 versus W5", fontsize=14)
    ax.legend(frameon=True)
    fig.tight_layout()

    out_png = out_dir / "figure_03_w4_w5_summary.png"
    out_pdf = out_dir / "figure_03_w4_w5_summary.pdf"
    fig.savefig(out_png, dpi=300)
    fig.savefig(out_pdf)
    plt.close(fig)

    print(f"[OK] Wrote: {out_png}")
    print(f"[OK] Wrote: {out_pdf}")


def figure_w4_w5_paired(subject_diffs: pd.DataFrame, out_dir: Path) -> pd.DataFrame:
    paired_stats = paired_stats_for_w4_w5(subject_diffs)

    # Build plotting table.
    rows = []
    for modality, roi, label in KEY_EFFECTS:
        sub = subject_diffs[
            (subject_diffs["contrast"] == "face_vs_nonface")
            & (subject_diffs["modality"] == modality)
            & (subject_diffs["roi"] == roi)
            & (subject_diffs["window"].isin(["W4", "W5"]))
        ].copy()

        if sub.empty:
            continue

        wide = sub.pivot_table(index="subject_id", columns="window", values="difference", aggfunc="mean")
        if "W4" not in wide.columns or "W5" not in wide.columns:
            continue

        wide = wide.dropna(subset=["W4", "W5"])
        for sid, r in wide.iterrows():
            rows.append({
                "subject_id": sid,
                "modality": modality,
                "roi": roi,
                "label": label,
                "W4": r["W4"],
                "W5": r["W5"],
                "W4_minus_W5": r["W4"] - r["W5"],
            })

    plot_df = pd.DataFrame(rows)
    if plot_df.empty:
        print("[WARN] No rows available for W4/W5 paired figure.")
        return paired_stats

    labels = list(dict.fromkeys(plot_df["label"].tolist()))
    n = len(labels)
    fig, axes = plt.subplots(1, n, figsize=(max(10, n * 2.2), 5), sharey=True)
    if n == 1:
        axes = [axes]

    for ax, label in zip(axes, labels):
        sub = plot_df[plot_df["label"] == label]
        for _, r in sub.iterrows():
            ax.plot([0, 1], [r["W4"], r["W5"]], marker="o", linewidth=1, alpha=0.55)
        ax.scatter([0], [sub["W4"].mean()], marker="D", s=55, zorder=4)
        ax.scatter([1], [sub["W5"].mean()], marker="D", s=55, zorder=4)
        ax.axhline(0, linestyle="--", linewidth=1)
        ax.set_xticks([0, 1])
        ax.set_xticklabels(["W4", "W5"])
        ax.set_title(label, fontsize=10)
        ax.set_xlim(-0.25, 1.25)

    axes[0].set_ylabel("Subject-level difference")
    fig.suptitle("Subject-level W4 to W5 change for Face - Non-face", fontsize=14)
    fig.tight_layout(rect=[0, 0, 1, 0.93])

    out_png = out_dir / "figure_04_w4_w5_paired_subjects.png"
    out_pdf = out_dir / "figure_04_w4_w5_paired_subjects.pdf"
    fig.savefig(out_png, dpi=300)
    fig.savefig(out_pdf)
    plt.close(fig)

    print(f"[OK] Wrote: {out_png}")
    print(f"[OK] Wrote: {out_pdf}")

    return paired_stats


def write_readme(out_dir: Path) -> None:
    readme = """# Final ERP Figures

This folder contains final, report-ready ERP figures generated by:

```bash
python scripts/03e_make_final_erp_figures.py --config configs/config.yaml
```

## Figures

1. `figure_01_face_nonface_difference_waves`
   - 2x2 panel of Face - Non-face difference waves.
   - Key ROIs: scalp late ROI, scalp face ROI, strict-ear, right-ear.

2. `figure_02_subject_level_w4_boxplot`
   - Subject-level W4 distributions for key ROIs.

3. `figure_03_w4_w5_summary`
   - W4 vs W5 descriptive summary.

4. `figure_04_w4_w5_paired_subjects`
   - Paired subject-level W4-to-W5 changes.

## Tables

- `final_figure_source_values.csv`
  - Source values used in the difference-wave figure.

- `final_w4_w5_paired_stats.csv`
  - Paired subject-level W4-W5 statistics.

## Scientific framing

The main result should be framed as a Face - Non-face stimulus-locked ERP effect,
not as participant-level emotion recognition.
"""
    (out_dir / "README.md").write_text(readme, encoding="utf-8")
    print(f"[OK] Wrote: {out_dir / 'README.md'}")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate final ERP figures for the LEMON/MELON analysis.")
    parser.add_argument("--config", default="configs/config.yaml", help="Path to config.yaml")
    parser.add_argument("--diff-dir", default="reports/erp_diff_sens", help="Input directory for sensitivity grand-average CSVs")
    parser.add_argument("--stats-dir", default="reports/stats_sens", help="Input directory for sensitivity subject-level stats")
    parser.add_argument("--out-dir", default="reports/final_figures", help="Output directory for final figures")
    args = parser.parse_args()

    config_path = Path(args.config)
    config = load_yaml(config_path)
    root = get_project_root(config)
    windows = get_windows(config)

    diff_dir = Path(args.diff_dir)
    stats_dir = Path(args.stats_dir)
    out_dir = Path(args.out_dir)

    if not diff_dir.is_absolute():
        diff_dir = root / diff_dir
    if not stats_dir.is_absolute():
        stats_dir = root / stats_dir
    if not out_dir.is_absolute():
        out_dir = root / out_dir

    ensure_dir(out_dir)

    subject_diffs_path = stats_dir / "subject_level_window_differences.csv"
    w4w5_summary_path = stats_dir / "w4_w5_interpretation_summary.csv"

    if not subject_diffs_path.exists():
        raise FileNotFoundError(f"Missing subject-level differences file: {subject_diffs_path}")
    if not w4w5_summary_path.exists():
        raise FileNotFoundError(f"Missing W4/W5 summary file: {w4w5_summary_path}")

    subject_diffs = pd.read_csv(subject_diffs_path)
    subject_diffs["subject_id"] = subject_diffs["subject_id"].astype(str)
    w4w5 = pd.read_csv(w4w5_summary_path)

    print(f"[INFO] Difference-wave input dir: {diff_dir}")
    print(f"[INFO] Subject-level stats dir: {stats_dir}")
    print(f"[INFO] Output dir: {out_dir}")

    # Figure 1
    source_values = figure_difference_waves(diff_dir, out_dir, windows)
    source_out = out_dir / "final_figure_source_values.csv"
    source_values.to_csv(source_out, index=False)
    print(f"[OK] Wrote: {source_out}")

    # Figure 2
    figure_subject_w4_boxplot(subject_diffs, out_dir)

    # Figure 3
    figure_w4_w5_summary(w4w5, out_dir)

    # Figure 4 + paired stats
    paired_stats = figure_w4_w5_paired(subject_diffs, out_dir)
    paired_out = out_dir / "final_w4_w5_paired_stats.csv"
    paired_stats.to_csv(paired_out, index=False)
    print(f"[OK] Wrote: {paired_out}")

    write_readme(out_dir)

    print("\n=== Final figure generation complete ===")
    print(f"Output folder: {out_dir}")
    print("\nKey files:")
    for name in [
        "figure_01_face_nonface_difference_waves.png",
        "figure_02_subject_level_w4_boxplot.png",
        "figure_03_w4_w5_summary.png",
        "figure_04_w4_w5_paired_subjects.png",
        "final_w4_w5_paired_stats.csv",
    ]:
        print(f"  - {out_dir / name}")


if __name__ == "__main__":
    main()
